### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by insticore** [insticore/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by classical-hyphen** [comment]
**2019**

Схопив праву ногу Джастіна Тімберлейка, коли той щойно прибув зі своєю дружиною Джессікою Біл.

**2017**

Поки Джамала виконувала свою пісню на фіналі Євробачення-2017, Седюк вибіг на сцену і, скинувши штани, показав свою "задню частину". Був оштрафований на 8,500 грн.

**2016**

Майже поцілував дупу Кім Кардашьян, коли вона прибула до ресторану L'Avenue.

Після модного показу в Мілані, Седюк прокрався за моделлю Джіджі Хадід і підняв її з землі, а потім навіть отримав від неї удар в обличчя. Покритикував Джіджі, звинувативши її, що вона не справжня модель "високої моди".

**2015**

Прокрався і поцілував у щоку Міранду Керр, коли вона відвідувала шоу злітно-посадкової смуги Louis Vuitton у Парижі.

Перед показом Valentino Седюк "напав" на співачку Сіару, яка позувала для фотографів. Віталій Седюк підійшов до співачки і скинув своє пальто, залишившись в сорочці і стрінгах (на стегні пранкери красувався напис Chanel).

**2014**

Схопив Бредлі Купера за ноги на 20-й премії Гільдії кіноакторів .

Кинувся до Леонардо Ді Капріо на Міжнародний кінофестиваль у Санта-Барбарі, ненадовго закопавши своє обличчя у пах Ді Капріо, перш ніж його видалили охоронці.

Під час показу мод бренду Prabal Gurung вибіг на сцену, одягнений в коротке пальто, стрінги з леопардовим принтом, червоні шкарпетки і золоту корону. Віталій навіть встиг добігти до моделей на подіумі.

На Каннському кінофестивалі проліз під сукню Америки Феррери. Феррера була "потрясена" інцидентом, а дехто навіть закликав звинуватити Седюка у сексуальному насильстві.

Штовхнув Кім Кардашьян і мало не повалив її на землю, якби не допомога її охоронця. Це було підтверджено після заяви Седюка, в якій зазначено: "Я сподіваюся, Кім в порядку і не буде сердитися на мене, оскільки я не мав на увазі жодної шкоди. Каньє - один щасливчик як Кім богиня! "

**2013**

Майже зміг увійти на церемонію 85th Academy Awards.

Віталій, який не мав ні квитка, ні посвідчень, вискочив на сцену під час премії "Греммі" 2013 року, коли Адель отримувала свою нагороду. В результаті інциденту Седюку було пред'явлено звинувачення у "навмисному залишенні зони для глядачів і вході в зону вистави", а також у "втручанні та затримці учасників програми". Отримав шестимісячний умовний термін.

**2012**

Поцілував Уілла Сміта на прем'єрі фільму "Люди в чорному 3" у Москві, через що Сміт вдарив його у обличчя і запитав "Якого біса, у тебе проблеми?". А Віталій ще й намагався взяти інтерв'ю у Сміта під час поцілунку.

**2011**

В прямому ефірі запропонував нареченій принца Уіл’яма Кейт Міддлтон руку та серце, а ще 10 соток землі в рідному Борисполі.

На Венеціанському кінофестивалі під час прес-конференції з нагоди виходу фільму W.E. Віталій вручив Мадонні букет з гортензій, які поп-королева викинула, це були квіти, які зірка нелюбила найбільш.
