### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by insticore** [insticore/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by classical-hyphen** [comment]
**Преса**

_Los Angeles Times_ описує його випади як "зловісні", тоді як _The Hollywood Reporter_ називає його "безсоромним прихильником уваги та бешкетником". 

У звіті про дії Седюка на Каннському кінофестивалі газета _HuffPost_, відзначаючи, що Седюк називає себе жартівником, запитала "чи хтось насправді сміється?" _New York_ описали Віталія як «Борат без дотепності або сатири», в той час як _Uproxx_ назвав його "виродком", а _The Wire_ "шматочком людського сміття".

Неамериканська преса також говорила про Седюка. Видання _GQ_ у Великобританії завило, що Седюк є поясненням "чому українська комедія ще не заволоділа світом", а _Toronto Star_ назвала його "несмішним пранкером".

**Мови**
Може зробити вигляд, що знає будь-якому мову, але достатньо володіє англійською, щоб потрапляти на зіркові події під виглядом іноземців.

**Досягнення**

Про Віталія неодноразово писали величезна кількість світових ЗМІ, а про моживі наслідки його поведінки у СІЗО натякав навіть сам Міністр внутрішніх справ України Арсен Аваков
https://www.facebook.com/arsen.avakov.1/posts/1393961047360664

Він мав змогу доторкнутись до зіркових красунь та красунчиків, або навіть отримати Гремі на сцені замість Адель.

Він побував у слідчих ізоляторів різних країн, був полапаний поліцією різних країн, облайнаний знаменитостями світового рівня.

**Навички**

Вміє пробиратись на добре захищені масштабні світські події, швидкий та раптовий, добре полює на "інтимні" частини тіла акторів та зірок.

**Особисте життя**

У 2012 році Седюк випустив короткометражний фільм під назвою «Гортензія» з бюджетом в 5000 доларів.
https://youtu.be/CNJcN3i_hMw
Він також працює як починаючий письменник, режисер та продюсер.
